CREATE TABLE promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    product_id TEXT NOT NULL,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT false,
    is_used BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ
);

COMMENT ON TABLE "public"."promo_codes" IS 'Stores promo codes that can be redeemed by users for in-app items.';

-- Seed the promo codes
INSERT INTO promo_codes (code, product_id) VALUES
('LIKE1PROMO', 'daaymn_like_1_p'),
('LIKE10PROMO', 'daaymn_like_10_p'),
('LIKE20PROMO', 'daaymn_like_20_p'),
('REPORTBASICPROMO', 'daaymn_report_basic_p'),
('REPORTPROPROMO', 'daaymn_report_pro_p'),
('REPORTDELUXEPROMO', 'daaymn_report_deluxe_p'),
('UNLOCKSCROLLINGPROMO', 'daaymn_unlock_scrolling_d'),
('UNLOCKVISIBILITYPROMO', 'daaymn_unlock_visibility_d'),
('SUBSTANDARDPROMO', 'daaymn_sub_standard_monthly_p'),
('SUBPROPROMO', 'daaymn_sub_pro_monthly_p'),
('SUBDELUXEPROMO', 'daaymn_sub_deluxe_monthly_p');
