-- increment_report_credit was executable by PUBLIC, so anyone holding the anon
-- key could grant themselves report credits through the REST RPC endpoint.
-- Only the service role (verify-google-purchase, grant-promo-item) should.
revoke execute on function public.increment_report_credit(uuid, text) from public, anon, authenticated;
grant execute on function public.increment_report_credit(uuid, text) to service_role;

-- grant-promo-item used to grant whatever productId the client sent, without
-- checking a code had been redeemed. Now redeem-promo-code records each
-- redemption here, and grant-promo-item can only claim an unclaimed one.
create table if not exists public.promo_redemptions (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  product_id  text not null,
  code        text not null,
  redeemed_at timestamptz not null default now(),
  claimed_at  timestamptz
);
create index if not exists promo_redemptions_unclaimed
  on public.promo_redemptions (user_id, product_id) where claimed_at is null;

-- Service role only: RLS on with no policies.
alter table public.promo_redemptions enable row level security;

-- Same checks as redeem_code_atomic, plus the redemption row, in one
-- transaction so a counted use always has a claimable redemption.
create or replace function public.redeem_promo_code(p_code text, p_user_id uuid)
returns table (product_id text, error_message text)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_promo public.promo_codes%rowtype;
begin
  select * into v_promo from public.promo_codes where code = p_code for update;

  if not found then
    return query select null::text, 'Promo code not found.'::text;
    return;
  end if;
  if not v_promo.is_active then
    return query select null::text, 'This promo code is not active.'::text;
    return;
  end if;
  if v_promo.expires_at is not null and v_promo.expires_at < now() then
    return query select null::text, 'This promo code has expired.'::text;
    return;
  end if;
  if v_promo.max_uses is not null and v_promo.times_used >= v_promo.max_uses then
    return query select null::text, 'This promo code has reached its usage limit.'::text;
    return;
  end if;

  update public.promo_codes set times_used = times_used + 1 where id = v_promo.id;
  insert into public.promo_redemptions (user_id, product_id, code)
  values (p_user_id, v_promo.product_id, v_promo.code);

  return query select v_promo.product_id, null::text;
end;
$$;

-- Marks one unclaimed redemption of this product as claimed and returns its id,
-- or null if there is none.
create or replace function public.claim_promo_redemption(p_user_id uuid, p_product_id text)
returns bigint
language sql
security definer
set search_path = pg_catalog, public
as $$
  update public.promo_redemptions
  set claimed_at = now()
  where id = (
    select id from public.promo_redemptions
    where user_id = p_user_id and product_id = p_product_id and claimed_at is null
    order by redeemed_at
    limit 1
    for update skip locked
  )
  returning id;
$$;

revoke execute on function public.redeem_promo_code(text, uuid) from public, anon, authenticated;
grant execute on function public.redeem_promo_code(text, uuid) to service_role;
revoke execute on function public.claim_promo_redemption(uuid, text) from public, anon, authenticated;
grant execute on function public.claim_promo_redemption(uuid, text) to service_role;

-- The old RPC is superseded by redeem_promo_code; calling it directly only
-- burned code uses, so close it to clients too.
revoke execute on function public.redeem_code_atomic(text) from public, anon, authenticated;
grant execute on function public.redeem_code_atomic(text) to service_role;
